language: python

python:
  - "3.7"

services:
  - postgresql

addons:
  postgresql: '9.4'

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - export DB_NAME="myhao"
  - psql -c 'create database myhao;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - coverage run --source='.' ./manage.py test
  - coverage report


after_script:
  - coveralls